selectors = [
	"p",
	"div",
	"div ~ p",
	"div > div",
	"div ~ div",
	"div > p",
	"body",
	"body div",
	"html body div",
	"div p",
	"div + p",
	"div ~ p",
	"div[class^=exa][class$=mple]",
	"div p a",
	"div, p, a",
	".note",
	"div.example",
	"ul .tocline2",
	"div.example, div.note",
	"#title",
	"h1#title",
	"div #title",
	"ul.toc li.tocline2",
	"ul.toc > li.tocline2",
	"h1#title + div > p",
	"h1[id]:contains(Selectors)",
	"a[href][lang][class]",
	"div[class]",
	"div[class=example]",
	"div[class^=exa]",
	"div[class$=mple]",
	"div[class*=e]",
	"div[class|=dialog]",
	"div[class!=made_up]",
	"div[class~=example]",
	"div:not(.example)",

	":enabled",
	":disabled",
	":checked",

	"p:contains(selectors)",
	"p:nth-child(even)",
	"p:nth-child(2n)",
	"p:nth-child(odd)",
	"p:nth-child(2n+1)",

	"p:nth-last-child(even)",
	"p:nth-last-child(2n)",
	"p:nth-last-child(odd)",
	"p:nth-last-child(2n+1)",
	"p:nth-child(n)",

	"p:nth-of-type(even)",
	"p:nth-of-type(2n)",
	"p:nth-of-type(odd)",
	"p:nth-of-type(2n+1)",

	"p:nth-last-of-type(even)",
	"p:nth-last-of-type(2n)",
	"p:nth-last-of-type(odd)",
	"p:nth-last-of-type(2n+1)",

	"p:only-child",
	"p:only-of-type",
	"p:last-child",
	"p:last-of-type",
	"p:first-child",
	"p:first-of-type"
];
